spring.application.name=OllamaApp
spring.ai.ollama.chat.model=qwen2.5
spring.ai.ollama.base-url=http://localhost:11434
spring.cloud.config.enabled=false
management.endpoint.refresh.enabled=true
management.endpoints.web.exposure.include=refresh